%YAML:1.0

# 1: realtime, 0: non-realtime
test.RealTime: 0
# Time for visual-inertial initialization
test.VINSInitTime: 15.0

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
test.InitVIOTmpPath: "/home/jh/temp/ssvo/"

## For good initialization (no movement at the beginning for some bag),需要设置，避免刚开始不动的那一段，后续需要移除这个参数
test.DiscardTime: 0
#bagfile: "/home/jp/TimeV1_01_easy.bag"
## bad: V1_03_difficult(wrong), V2_03_difficult(lost)
## not so good(cant close loop without loopclosure): V1_02_medium, V2_02_medium, MH_05_difficult
## good: V1_01_easy, V2_01_easy, MH_01_easy, MH_02_easy, MH_03_medium, MH_04_difficult

#test.DiscardTime: 18
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_03_medium.bag"

#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_04_difficult.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_05_difficult.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_02_easy.bag"
bagfile: "/home/jh/MH_01_easy.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V2_02_medium.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V2_01_easy.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V1_02_medium.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V1_01_easy.bag"

#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V1_03_difficult.bag"
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/V2_03_difficult.bag"

#######################################

imutopic: "/imu0"
imagetopic: "/cam0/image_raw"


# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# Local Window size
LocalMapping.LocalWindowSize: 30

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
 [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
  0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
  -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
  0.0, 0.0, 0.0, 1.0]
